# Generated by Django 4.2.1 on 2024-05-27 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_producto_marca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='marca',
        ),
    ]
