# Generated by Django 4.2.1 on 2024-05-26 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_entregapedido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entregapedido',
            options={'ordering': ['id'], 'verbose_name': 'Entrega Pedido', 'verbose_name_plural': 'Entrega Pedidos'},
        ),
        migrations.AlterModelTable(
            name='entregapedido',
            table='entregapedido',
        ),
    ]
