# Generated by Django 4.2.1 on 2024-05-27 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_alter_entregapedido_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='entregapedido',
            table='entregapedidos',
        ),
    ]
