# Generated by Django 4.2.1 on 2024-05-27 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_alter_entregapedido_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='entregapedido',
            table='entregapedido',
        ),
    ]
